name: ci
on: 
  push:
  workflow_dispatch:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Run Tests
        run: |
          bundle exec rake test
  custom-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Run Custom Tests
        run: |
          bundle exec rake customtest
  publish:
    runs-on: ubuntu-latest
    needs: [unit-tests]  # Only publish if unit tests pass
    if: github.ref == 'refs/heads/main'  # Only publish from main branch
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBY_GEMS_API_KEY }}
        run: |
          gem build *.gemspec
          gem push *.gem
